### PR TITLE
add support for differeing line endings

### PR DESCRIPTION
**Pull request by itslenny**
Use regex instead of os.EOL to support mixed line endings.

See #4

### CODE REVIEW

**Comment by vitaly-t** [comment]
@itslenny I've just released a proper 0.8.0 with everything you need ;) Will update grunt + gulp plug-ins in a few minutes ;)

**Comment by itslenny** [comment]
This is not really what I was looking for. The files are inconsistent so I don't know what the line endings are so I cannot specify. I created a pull request that uses a regex instead of assuming OS line endings would match the files line endings.

Unfortunately, this pull request conflicts with the one you just added so I'll refactor and re-submit.

**Comment by vitaly-t** [comment]
>The files are inconsistent so I don't know what the line endings are so I cannot specify.
`platform = "auto"` will do the trick.

**Comment by vitaly-t** [comment]
@itslenny both gulp and grunt plugins have been updated and released. Check that out!

**Pull request closed without merging**
